import "./globals.css";
import Navbar from "@/app/component/navbar"
import Header from "@/app/component/header"
import { Poppins } from '@next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata = {
  title: "Taskly",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=''>
      <body
        className={`${poppins.className} bg-[#F7F7F7] w-100% min-h-dvh`}
      >
        <div className='flex w-[100%]'>
          <Navbar />
          <div className='w-[100%]'>
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
