import "./globals.css";
import { Poppins } from 'next/font/google';
import { UserProvider } from '@/context/UserContext';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata = {
  title: "Taskly",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" className='no-scrollbar'>
      <body
        className={`${poppins.className} bg-[#F7F7F7]`}
      >
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
