import "./globals.css";
import Navbar from "@/app/component/navbar"
import Header from "@/app/component/header"
import { Poppins } from '@next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata = {
  title: "Taskly",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='no-scrollbar'>
      <body
        className={`${poppins.className} bg-[#F7F7F7]`}
      >
        <div className='flex flex-row w-[100%]'>
          <Navbar />
          <div className='w-full'>
            <Header />
            <div className='px-[30px] w-full'>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
